### PR TITLE
s33zeng mentor commit

### PR DESCRIPTION
**Pull request by s-zeng**
Tagging @Azhng and @9at8 as reviewers.

### CODE REVIEW

**Comment by Azhng** [comment]
Please rebase against the master branch since we just updated the event time

**Comment by s-zeng** [comment]
Rebased @Azhng 

Also, March 2 is a Saturday, not a Monday. Should this be updated?

**Comment by Azhng** [comment]
@s-zeng  my bad. Fixed it in the master branch. Sorry you need to rebase again

**Comment by s-zeng** [comment]
Rebased again @Azhng

**Review by 9at8 — APPROVED** [review]

**Comment by 9at8** [comment]
:shipit:

**Pull request merged**
